// <auto-generated />
using System;
using Grupo422021.Web1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Grupo422021.Web1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211018171858_detalleordenservicio")]
    partial class detalleordenservicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Grupo422021.Web1.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Mecanico", b =>
                {
                    b.Property<int>("IdMecanico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdMecanico");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.OrdenServicio", b =>
                {
                    b.Property<int>("IdOrdenServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdMecanico")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrdenServicio");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMecanico");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("OrdenServicio");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.OrdenServicioDetalle", b =>
                {
                    b.Property<int>("IdOrdenServicioDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdOrdenServicioDetalle");

                    b.HasIndex("IdOrdenServicio");

                    b.HasIndex("IdServicio");

                    b.ToTable("OrdenServicioDetalle");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdServicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMarca");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.OrdenServicio", b =>
                {
                    b.HasOne("Grupo422021.Web1.Models.Cliente", "Cliente")
                        .WithMany("OrdenServicio")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grupo422021.Web1.Models.Mecanico", "Mecanico")
                        .WithMany()
                        .HasForeignKey("IdMecanico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grupo422021.Web1.Models.Vehiculo", "Vehiculo")
                        .WithMany("OrdenServicio")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Mecanico");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.OrdenServicioDetalle", b =>
                {
                    b.HasOne("Grupo422021.Web1.Models.OrdenServicio", "OrdenServicio")
                        .WithMany("OrdenServicioDetalle")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grupo422021.Web1.Models.Servicio", "Servicio")
                        .WithMany("OrdenServicioDetalle")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Vehiculo", b =>
                {
                    b.HasOne("Grupo422021.Web1.Models.Cliente", "Cliente")
                        .WithMany("Vehiculo")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grupo422021.Web1.Models.Marca", "Marca")
                        .WithMany("Vehiculo")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Cliente", b =>
                {
                    b.Navigation("OrdenServicio");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Marca", b =>
                {
                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.OrdenServicio", b =>
                {
                    b.Navigation("OrdenServicioDetalle");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Servicio", b =>
                {
                    b.Navigation("OrdenServicioDetalle");
                });

            modelBuilder.Entity("Grupo422021.Web1.Models.Vehiculo", b =>
                {
                    b.Navigation("OrdenServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
